name: 'CI'
on: push
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2         # checkout the repo
      - run: npm install                  # install packages
      - run: npm test                     # run tests (configured to use jest-junit reporter)
      - uses: actions/upload-artifact@v2  # upload test results
        if: always()        # run this step even if previous step failed
        with:
          name: test-results
          path: test-results.json
          reporter: mocha-json
